clauses/urls.py
from django.urls import path

from . import views

app_name = "clauses"
urlpatterns = [
    # ex: /clauses/
    path("", views.index, name="index"),
    # ex: /clauses/5/
    path("<int:clause_id>/", views.detail, name="detail"),
    # ex: /clauses/5/rate/
    path("<int:clause_id>/rate/", views.rate, name="rate"),
]

clauset/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("clauses/", include("clauses.urls")),
    path('admin/', admin.site.urls),
]

clauses/models.py
"""Models for clauset."""

import datetime

from django.db import models
from django.utils import timezone


class Clause(models.Model):
    """Contract clauses."""

    ALABAMA = "AL"
    ALASKA = "AK"
    ARIZONA = "AZ"
    ARKANSAS = "AR"
    CALIFORNIA = "CA"
    COLORADO = "CO"
    CONNECTICUT = "CT"
    DELAWARE = "DE"
    FLORIDA = "FL"
    GEORGIA = "GA"
    HAWAII = "HI"
    IDAHO = "ID"
    ILLINOIS = "IL"
    INDIANA = "IN"
    IOWA = "IA"
    KANSAS = "KS"
    KENTUCKY = "KY"
    LOUISIANA = "LA"
    MAINE = "ME"
    MARYLAND = "MD"
    MASSACHUSETTS = "MA"
    MICHIGAN = "MI"
    MINNESOTA = "MN"
    MISSISSIPPI = "MS"
    MISSOURI = "MO"
    MONTANA = "MO"
    NEBRASKA = "NE"
    NEVADA = "NV"
    NEW_HAMPSHIRE = "NH"
    NEW_JERSEY = "NJ"
    NEW_MEXICO = "NM"
    NEW_YORK = "NY"
    NORTH_CAROLINA = "NC"
    NORTH_DAKOTA = "ND"
    OHIO = "OH"
    OKLAHOMA = "OK"
    OREGON = "OR"
    PENNSYLVANIA = "PA"
    RHODE_ISLAND = "RI"
    SOUTH_CAROLINA = "SC"
    SOUTH_DAKOTA = "SD"
    TENNESSEE = "TN"
    TEXAS = "TX"
    UTAH = "UT"
    VERMONT = "VT"
    VIRGINIA = "VA"
    WASHINGTON = "WA"
    WEST_VIRGINIA = "WV"
    WISCONSIN = "WI"
    WYOMING = "WY"
    UNKNOWN = "UK"
    GOVERNING_LAW_CHOICES = [
        (ALABAMA, "Alabama"),
        (ALASKA, "Alaska"),
        (ARIZONA, "Arizona"),
        (ARKANSAS, "Arkansas"),
        (CALIFORNIA, "California"),
        (COLORADO, "Colorado"),
        (CONNECTICUT, "Connecticut"),
        (DELAWARE, "Delaware"),
        (FLORIDA, "Florida"),
        (GEORGIA, "Georgia"),
        (HAWAII, "Hawaii"),
        (IDAHO, "Idaho"),
        (ILLINOIS, "Illinois"),
        (INDIANA, "Indiana"),
        (IOWA, "Iowa"),
        (KANSAS, "Kansas"),
        (KENTUCKY, "Kentucky"),
        (LOUISIANA, "Louisana"),
        (MAINE, "Maine"),
        (MARYLAND, "Maryland"),
        (MASSACHUSETTS, "Massachusetts"),
        (MICHIGAN, "Michigan"),
        (MINNESOTA, "Minnesota"),
        (MISSISSIPPI, "Mississippi"),
        (MISSOURI, "Missouri"),
        (MONTANA, "Montana"),
        (NEBRASKA, "Nebraska"),
        (NEVADA, "Nevada"),
        (NEW_HAMPSHIRE, "New Hampshire"),
        (NEW_JERSEY, "New Jersey"),
        (NEW_MEXICO, "New Mexico"),
        (NEW_YORK, "New York"),
        (NORTH_CAROLINA, "North Carolina"),
        (NORTH_DAKOTA, "North Dakota"),
        (OHIO, "Ohio"),
        (OKLAHOMA, "Oklahoma"),
        (OREGON, "Oregon"),
        (PENNSYLVANIA, "Pennsylvania"),
        (RHODE_ISLAND, "Rhode Island"),
        (SOUTH_CAROLINA, "South Carolina"),
        (SOUTH_DAKOTA, "South Dakota"),
        (TENNESSEE, "Tennessee"),
        (TEXAS, "Texas"),
        (UTAH, "Utah"),
        (VERMONT, "Vermont"),
        (VIRGINIA, "Virginia"),
        (WASHINGTON, "Washington"),
        (WEST_VIRGINIA, "West Virginia"),
        (WISCONSIN, "Wisconsin"),
        (WYOMING, "Wyoming"),
        (UNKNOWN, "Unknown"),
    ]

    text = models.CharField(max_length=2000, default="")
    topic = models.CharField(max_length=200)
    contract_type = models.CharField(max_length=200)
    # Date that clause was approved to be added to db
    pub_date = models.DateTimeField()
    # Effective date of contract in which clause appears.
    effective_date = models.DateField()
    gov_law = models.CharField(
        "governing law",
        max_length=2,
        choices=GOVERNING_LAW_CHOICES,
        default=UNKNOWN,
        )

    def __str__(self):
        return f'{self.topic} ({self.pub_date.date()}): "{self.text[:50]}"'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=7)


class Rating(models.Model):
    """Up/downvotes and reports from users on contract clauses."""

    clause = models.ForeignKey(Clause, on_delete=models.CASCADE)
    user = models.CharField(max_length=200, default="")
    value = models.CharField(
        max_length=1,
        choices=[
            ("U", "upvote"),
            ("D", "downvote"),
            ("R", "report"),
            ("N", "none")
        ],
        default="N"
    )
    report_reason = models.CharField(max_length=2000)

clauses/views.py
"""Views for clauses app."""

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Clause, Rating


# Homempage.
def index(request):
    latest_clause_list = Clause.objects.order_by("-pub_date")[:5]
    context = {"latest_clause_list": latest_clause_list}
    return render(request, "clauses/index.html", context)


# Detail for a single clause.
def detail(request, clause_id):
    clause = get_object_or_404(Clause, pk=clause_id)
    return render(request, "clauses/detail.html", {"clause": clause})


# Submit a rating for a single clause.
def rate(request, clause_id):
    clause = get_object_or_404(Clause, pk=clause_id)

    try:
        value = request.POST["rating"]
        rating = Rating(
            clause=clause,
            value=value,
        )
    except (KeyError, Clause.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "clauses/detail.html",
            {
                "error_message": "You didn't provide a reason for reporting.",
            },
        )
    else:
        rating.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("clauses:deatil", args=(clause.id)))

clauses/templates/clauses/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Clause Detail</title>
</head>

<body>
  <h2>{{ clause.topic }}</h2>
  <p>{{ clause.text }}</p>
  <p>Info:</p>
  <ul>
    <li>Published: {{ clause.pub_date }}</li>
    <li>Contract Type: {{ clause.contract_type }}</li>
    <li>Effective Date: {{ clause.effective_date }}</li>
    <li>Governing Law: {{ clause.gov_law }}</li>
  </ul>
  <form action="{% url 'clauses:rate' clause.id %}" method="post">
    {% csrf_token %}
    <fieldset>
      <!-- <legend>
        <h1>{{ clause.text }}</h1>
      </legend> -->
      <input type="hidden" name="rating" value="U">
      <button type="submit" id="upvote-button">Upvote</button>
      <input type="hidden" name="rating" value="D">
      <button type="submit" id="downvote-button">Downvote</button><br>
      <label for="report-reason">Reason for reporting:</label>
      <input type="text" name="report_reason" >
      <button type="submit" name="rating" value="R">Report</button>
    </fieldset>
  </form>
</body>

</html>

clauses/templates/clauses/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Homepage</title>
</head>

<body>
  {% if latest_clause_list %}
  <ul>
    {% for clause in latest_clause_list %}
    <li>
      <a href="{% url 'clauses:detail' clause.id %}">{{ clause.text }}</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No clauses are available.</p>
  {% endif %}
</body>

</html>